### ISSUE TITLE
Visual bug: Banner covers text

### ISSUE THREAD

**Issue by MindokRuvaak** [Jourmumriken/Real-Housewives-Of-Agile#1]
Footer-banner covers text in guide on smaller resolution windows.

![image](https://github.com/user-attachments/assets/74263cef-4383-46fa-b93b-9540905a5f77)

**Comment by MindokRuvaak** [comment]
Also left-side navigation-bar does not stretch all the way down to the bottom of the window.

**Comment by Jourmumriken** [comment]
on it

**Comment by Jourmumriken** [comment]
i was in fact not on it lol

**Comment by MindokRuvaak** [comment]
It's back

**Comment by MindokRuvaak** [comment]
fixed again
