### ISSUE TITLE
Java server wont serve index.html (or anything for that matter)

### ISSUE THREAD

**Issue by Jourmumriken** [Jourmumriken/Real-Housewives-Of-Agile#2]
When launching Main.java through vsCodes debugger (Compiling manually also did not work for me, but I havent tried it super extensivley) It starts but does not serve a website and instead gives a 404 exception and crashes. Why this is idk but it seems it only happens for me and not yousef? Maybe its linux related?

**Comment by O-Brob** [comment]
> When launching Main.java through vsCodes debugger (Compiling manually also did not work for me, but I havent tried it super extensivley) It starts but does not serve a website and instead gives a 404 exception and crashes. Why this is idk but it seems it only happens for me and not yousef? Maybe its linux related?

Tried on a VM running EndeavourOS, works for me via vscode by running Main.java and opening localhost:8080 on firefox. Could maybe be that you have something that already occupies port 8080 on your local network. Have you tried changing it in MultiPageHttpServer.java to something else, like 8081 or similar? c:

**Comment by Jourmumriken** [comment]
I forgot to remove this, I think it was user error but I don't know what I did different lol
